apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio
  namespace: default
spec:
  dnsNames:
    - portfolio.ujstor.com
  secretName: portfolio-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer